##
# Solution target
#
# The solution target builds
# the solution and result classes.
#
solution:
	javac *.java -Xlint

##
# Clean target
#
# The clean target removes
# all Java class files.
#
clean:
	rm *.class
